run_title: ''

training_model:
  kind: defaultS2
  visualize_each_iters: 1000
  concat_mask: true
  store_discr_outputs_for_vis: true
  generatorS2_path: /home/b109/Desktop/XX/inpainting/result/train/S1forS2/mri-S1-masklab_pei_S1162_1w2_light4_kw.pth
  generatorS1_path: /home/b109/Desktop/XX/inpainting/result/train/S1forS2/mri-S1-masklab_pei_S1162_1w2_light4_kw.pth
losses:
  l1:
    weight_missing: 0
    weight_known: 10
  kd:
    loss_weight: 1.0
    temperature: 0.15
  perceptual:
    weight: 0
  adversarial:
    kind: r1
    weight: 10
    gp_coef: 0.001
    mask_as_fake_target: true
    allow_scale_mask: true
  feature_matching:
    weight: 100
  resnet_pl:
    weight: 30
    weights_path: ${env:TORCH_HOME}

defaults:
  - location: mri
  - data: abl-04-256-mh-dist-mri
  - generatorT: DiffIRS1-mri
  - generator: DiffIRS2-mri
  - discriminator: pix2pixhd_nlayer
  - optimizers: default_optimizers
  - visualizer: directory
  - evaluator: default_inpainted
  - trainer: any_gpu_large_ssim_ddp_final_mriS
  - hydra: overrides
