# @package _group_
kind: DiffIRS2
n_encoder_res: 8
inp_channels: 4
out_channels: 3
dim: 52
num_blocks: [1,1,1,20]
num_refinement_blocks: 0
heads: [1,2,4,8]
ffn_expansion_factor: 1.8
bias: False
LayerNorm_type: WithBias
dual_pixel_task: False
n_denoise_res: 1
linear_start: 0.1
linear_end: 0.99
timesteps: 4
